### !!! change the uuid with an existing one
GET http://localhost:9999/api/library/books/18ad8511-af26-4327-ab2d-b046269185ff
Accept: application/json

###
GET http://localhost:9999/api/library/books
Accept: application/json

### Valid data
POST http://localhost:9999/api/library/books
Content-Type: application/json

{
    "title": "Testing metadata v1",
    "author_name": "John Doe",
    "year_of_publication": 2023
}

### Invalid data
POST http://localhost:9999/api/library/books
Content-Type: application/json

{
    "title": "Api Book",
    "author_name": "John Doe",
    "year_of_publication": "invalid"
}

###  !!! change the uuid with an existing one
PATCH http://localhost:9999/api/library/books/36af30ca-319c-4b63-b958-339d30dea3dd
Content-Type: application/json

{
    "uuid": "18ad8511-af26-4327-ab2d-b046269185ff",
    "title": "Api Book Volume 2, 2eme édition",
    "author_name": "John Doe",
    "year_of_publication": 2022
}

### invalid put  !!! change the uuid with an existing one
PUT http://localhost:9999/api/library/books/cfdd4fd5-1378-4b73-a9fd-00aeff713ffc
Content-Type: application/json

{
    "uuid": "18ad8511-af26-4327-ab2d-b046269185ff",
    "author_name": "John Doe",
    "year_of_publication": 2022
}

### !!! change the uuid with an existing one
PUT http://localhost:9999/api/library/books/cfdd4fd5-1378-4b73-a9fd-00aeff713ffc
Content-Type: application/json

{
    "uuid": "cfdd4fd5-1378-4b73-a9fd-00aeff713ffc",
    "title": "Api Book Volume 3",
    "author_name": "John Doe",
    "year_of_publication": 2023
}

### !!! change the uuid with an existing one
DELETE http://localhost:9999/api/library/books/88ba4c8a-0a04-4a64-8baa-6d4bd2910707
Accept: application/json

### book not exists => 404
DELETE http://localhost:9999/api/library/books/11111111-aaaa-2222-bbbb-333333333333
Accept: application/json


