###
GET http://127.0.0.1:9999/api/library/subscribers
Accept: application/json

### !!! change the uuid with an existing one
GET http://127.0.0.1:9999/api/library/subscribers/0c44d2b7-b4ba-42de-bd24-81bb2577fbca
Accept: application/json

###
POST http://localhost:9999/api/library/subscribers
Content-Type: application/json

{
    "first_name": "Tony",
    "last_name": "Stark",
    "email": "iron.man@example.org"
}

### invalid request email exists for another user
POST http://localhost:9999/api/library/subscribers
Content-Type: application/json

{
    "first_name": "Helene",
    "last_name": "DeTroie",
    "email": "jane.doe@example.org"
}

###
PATCH http://localhost:9999/api/library/subscribers/0c44d2b7-b4ba-42de-bd24-81bb2577fbca
Content-Type: application/json

{
    "first_name": "Alphonse",
    "last_name": "Danlemur",
    "email": "alphone.danlemur@example.org"
}

### invalid request email exists for another user
PATCH http://localhost:9999/api/library/subscribers/0c44d2b7-b4ba-42de-bd24-81bb2577fbca
Content-Type: application/json

{
    "email": "jane.doe@example.org"
}

### invalid  email
PATCH http://localhost:9999/api/library/subscribers/0c44d2b7-b4ba-42de-bd24-81bb2577fbca
Content-Type: application/json

{
    "email": "jane.doe@example"
}

### !!! change the uuid with an existing one
DELETE http://localhost:9999/api/library/subscribers/79a191d4-b0ec-419a-b33f-4192b5dcf6f1
Accept: application/json

###
POST http://localhost:9999/api/library/subscribers/0c44d2b7-b4ba-42de-bd24-81bb2577fbca/books
Content-Type: application/json

{
    "books": [
        "36af30ca-319c-4b63-b958-339d30dea3dd",
        "18ad8511-af26-4327-ab2d-b046269185ff",
        "18ad8511-af26-4327-ab2d-b04626918500",
        "f53de3e4-edcc-4554-880a-19864e90ef0f"
    ]
}

###
POST http://localhost:9999/api/library/subscribers/835d6a96-2c40-47c8-abfe-e383ca9614e5/books
Content-Type: application/json

{
    "books": [
        "df644509-09ee-431f-b867-ac00f5539ff9",
        "18ad8511-af26-4327-ab2d-b046269185ff",
        "cfdd4fd5-1378-4b73-a9fd-00aeff713ffc"
    ]
}

###
DELETE http://localhost:9999/api/library/subscribers/109e422a-bf7d-4ce1-9a26-1d6df6961982/books/cfdd4fd5-1378-4b73-a9fd-00aeff713ffc
Accept: application/json
