version: '3.7'

networks:
  library_network:
    driver: bridge

volumes:
  library_database_volume:
    driver: "local"

services:

  library_database:
    container_name: library_database
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    networks:
      - library_network
    volumes:
      - library_database_volume:/var/lib/postgresql/data:rw
    ports:
      - "5440:5432"

  library_php:
    image: php-dev:8.0.10
    build: ./docker/php
    container_name: library_php
    networks:
      - library_network
    volumes:
      - ./../../Library:/Library
    working_dir: /Library
    depends_on:
      - library_database

  library_nginx:
    container_name: library_nginx
    image: nginx:1.19
    networks:
      - library_network
    volumes:
      - ./../../Library:/Library
      - ./volumes/etc/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /Library
    depends_on:
      - library_php
    ports:
      - "9999:80"
